### PR TITLE
Fixing link to California's absentee ballot request form

### PR DESCRIPTION
**Pull request by ChrisAntaki**

### CODE REVIEW

**Comment by schneidmaster** [comment]
Hey thanks for the PR! I actually just had a California staffer note the same thing, but she requested I use a different link (http://www.sos.ca.gov/elections/voting-resources/voting-california/where-and-how-vote/#get-a-ballot) so people can see additional details besides just the form. But thanks for contributing!

**Comment by ChrisAntaki** [comment]
Nice, glad it got sorted out. :smile: 

For some reason that new link redirects to http://www.sos.ca.gov/elections/where-and-how after ~15 seconds.

**Comment by schneidmaster** [comment]
Oh huh, that's no good. Gotta love quality websites. I'll figure it out, thanks for noting.

**Comment by ChrisAntaki** [comment]
Linking to a copy of the PDF on S3 or Dropbox could work well too. That way HTTPS could be maintained throughout. :lock:

**Pull request closed without merging**
